In [3]:
import numpy as np
np.random.normal()

0.16774447696798084

In [6]:
np.random.normal(size=4)

array([ 1.23536402,  1.71920757, -0.95987286, -0.53240673])

In [7]:
data = np.random.normal(size=10) # generating 10 digit in Normal Distribution

In [8]:
data

array([ 1.45707881,  0.09516821,  1.10423728, -0.17153278, -0.14817408,
       -0.22929194,  0.27321664, -0.67443886, -1.1355904 ,  1.44425075])

In [9]:
data * 10 #matrix multiplication

array([ 14.57078813,   0.95168212,  11.04237275,  -1.71532776,
        -1.48174076,  -2.29291943,   2.73216638,  -6.74438861,
       -11.35590396,  14.44250749])

In [10]:
data + data #matrix Addition

array([ 2.91415763,  0.19033642,  2.20847455, -0.34306555, -0.29634815,
       -0.45858389,  0.54643328, -1.34887772, -2.27118079,  2.8885015 ])

In [12]:
data.shape # (rows,columns)

(10,)

In [13]:
data.dtype #datatype

dtype('float64')

In [16]:
data1 = [6,7.0,8.9,9,10]
arr1 = np.array(data1)
arr1

array([  6. ,   7. ,   8.9,   9. ,  10. ])

In [17]:
arr1.dtype

dtype('float64')

In [18]:
data2 = [[1,2,3,4],[6,7,8,9]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [19]:
arr2.ndim # dimension of the matrix

2

In [20]:
arr2.shape

(2, 4)

In [21]:
np.ones(2) 

array([ 1.,  1.])

In [22]:
np.zeros((3,6)) # creates 3x6 matrix of Zeros

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [23]:
np.empty((2,3,2)) # creates 2 '3x2' matrix with random numbers assigned !

array([[[ -2.00000000e+000,  -2.00000000e+000],
        [  3.45845952e-323,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]]])

In [24]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
arr = np.array([-4.3,-2.0,1.9,-2.7])#floating point array
arr.dtype

dtype('float64')

In [28]:
arr.astype(int) # converting floating array to Int typr

array([-4, -2,  1, -2])

In [31]:
empty_uint32 = np.empty(8,dtype='u4')
empty_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [32]:
arr = np.array([[1,2,4],[2,4,6]])
print(arr) # print array
print(arr*arr) # print array multiplication
print(arr/4) # print array Division
print(arr**2) # power of an array

[[1 2 4]
 [2 4 6]]
[[ 1  4 16]
 [ 4 16 36]]
[[ 0.25  0.5   1.  ]
 [ 0.5   1.    1.5 ]]
[[ 1  4 16]
 [ 4 16 36]]


In [37]:
# basic indexing and slicing 
varNum = np.arange(10)
print(varNum)
print(varNum[4])
print(varNum[4:9])
varNum[4:9] = 10
print(varNum)

[0 1 2 3 4 5 6 7 8 9]
4
[4 5 6 7 8]
[ 0  1  2  3 10 10 10 10 10  9]


In [38]:
varNum_slice = varNum[1:4] # it replaces value in an array with a mentioned in array index 
print(varNum_slice)
print(varNum_slice[1])
varNum_slice[1] = 12345
print(varNum) # change in X in reflected in Y

[1 2 3]
2
[    0     1 12345     3    10    10    10    10    10     9]


In [39]:
varNum_slice[:] = 64

In [41]:
varNum

array([ 0, 64, 64, 64, 10, 10, 10, 10, 10,  9])

In [51]:
newArr = data2.copy() # Copy array  from another array !

In [52]:
newArr

[[1, 2, 3, 4], [6, 7, 8, 9]]

In [53]:
arr2d = np.array([[1,2,3,4],[4,5,6,7],[2,1,3,5],[8,3,5,4]]) # 4x4 array

In [54]:
print(arr2d)

[[1 2 3 4]
 [4 5 6 7]
 [2 1 3 5]
 [8 3 5 4]]


In [55]:
arr2d[2]

array([2, 1, 3, 5])

In [57]:
arr2d[0][2] # accessing element at position 0x2 i.e 1st row 3rd column

3

In [58]:
# Three Dimensional Array 
arr3d = np.array([[[1,2,3],[2,3,4]],[[4,5,6],[5,6,7]]])
arr3d

array([[[1, 2, 3],
        [2, 3, 4]],

       [[4, 5, 6],
        [5, 6, 7]]])

In [59]:
arr3d.shape # 2 arrays with 2x3 dimension !

(2, 2, 3)

In [60]:
arr3d[0]

array([[1, 2, 3],
       [2, 3, 4]])

In [65]:
old_values = arr3d[0].copy()
old_values

array([[42, 42, 42],
       [42, 42, 42]])

In [66]:
arr3d[0] = 42

In [67]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 4,  5,  6],
        [ 5,  6,  7]]])

In [68]:
arr3d[0] = old_values

In [70]:
print(arr3d[0])

[[42 42 42]
 [42 42 42]]


In [71]:
arr3d[1,0]

array([4, 5, 6])

In [74]:
#one dimensional array
arrval = np.arange(10)
arrval[1:6]

array([1, 2, 3, 4, 5])

In [75]:
arrval

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr2d # prints whole matrix

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [2, 1, 3, 5],
       [8, 3, 5, 4]])

In [77]:
arr2d[:2] # prints matrix[rows,columns] i.e rows = :2 means two rows including all column (:2,:) it means 2 rows with all columns

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [78]:
arr2d[:2,:1]

array([[1],
       [4]])

In [79]:
arr2d[1,:2]

array([4, 5])

In [80]:
arr2d[2,:1]

array([2])

In [81]:
arr2d[:,:1]

array([[1],
       [4],
       [2],
       [8]])

In [82]:
arr2d[:2,1:]

array([[2, 3, 4],
       [5, 6, 7]])

In [83]:
arr2d[:2,1:] = 0

In [91]:
names = np.array(['Ace','Bob','Cave','Dave','Effiy','Fred'])
data = np.random.rand(7,4)
names

array(['Ace', 'Bob', 'Cave', 'Dave', 'Effiy', 'Fred'], 
      dtype='<U5')

In [92]:
data

array([[ 0.33005871,  0.43429875,  0.04109162,  0.58486669],
       [ 0.84723973,  0.71032989,  0.36302576,  0.21786784],
       [ 0.77869135,  0.22354758,  0.98819085,  0.02343568],
       [ 0.16797632,  0.32847168,  0.32822675,  0.32415245],
       [ 0.86731215,  0.49971504,  0.43651558,  0.78273655],
       [ 0.14521813,  0.41239516,  0.18686248,  0.33716942],
       [ 0.88661176,  0.01245236,  0.57048233,  0.5382866 ]])

In [93]:
data.shape

(7, 4)

In [94]:
names == 'Bob'

array([False,  True, False, False, False, False], dtype=bool)

In [95]:
data[names == 'Bob']

/Users/mayurjain/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 6
  """Entry point for launching an IPython kernel.


array([[ 0.84723973,  0.71032989,  0.36302576,  0.21786784]])

In [96]:
data[names == 'Bob',2:]

/Users/mayurjain/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 6
  """Entry point for launching an IPython kernel.


array([[ 0.36302576,  0.21786784]])

In [97]:
data[names == 'Bob',3]

/Users/mayurjain/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 6
  """Entry point for launching an IPython kernel.


array([ 0.21786784])

In [98]:
names != 'Bob'

array([ True, False,  True,  True,  True,  True], dtype=bool)

In [99]:
data[-(names == 'Bob')]

/Users/mayurjain/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.
  """Entry point for launching an IPython kernel.
/Users/mayurjain/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 6
  """Entry point for launching an IPython kernel.


array([[ 0.33005871,  0.43429875,  0.04109162,  0.58486669],
       [ 0.77869135,  0.22354758,  0.98819085,  0.02343568],
       [ 0.16797632,  0.32847168,  0.32822675,  0.32415245],
       [ 0.86731215,  0.49971504,  0.43651558,  0.78273655],
       [ 0.14521813,  0.41239516,  0.18686248,  0.33716942]])

In [100]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([False,  True, False, False, False, False], dtype=bool)

In [101]:
data[mask]

/Users/mayurjain/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 6
  """Entry point for launching an IPython kernel.


array([[ 0.84723973,  0.71032989,  0.36302576,  0.21786784]])

In [104]:
data[data < 0.3] = 0 

In [105]:
data

array([[ 0.33005871,  0.43429875,  0.        ,  0.58486669],
       [ 0.84723973,  0.71032989,  0.36302576,  0.        ],
       [ 0.77869135,  0.        ,  0.98819085,  0.        ],
       [ 0.        ,  0.32847168,  0.32822675,  0.32415245],
       [ 0.86731215,  0.49971504,  0.43651558,  0.78273655],
       [ 0.        ,  0.41239516,  0.        ,  0.33716942],
       [ 0.88661176,  0.        ,  0.57048233,  0.5382866 ]])

In [106]:
data[names!='Ace'] = 7

/Users/mayurjain/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 6
  """Entry point for launching an IPython kernel.


In [107]:
data

array([[ 0.33005871,  0.43429875,  0.        ,  0.58486669],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.88661176,  0.        ,  0.57048233,  0.5382866 ]])