In [1]:
#fancy indexing
import numpy as np
arr = np.empty((8,4))
arr

array([[ -0.00000000e+000,  -0.00000000e+000,  -7.90505033e-323,
          0.00000000e+000],
       [  2.12199579e-314,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  1.75871011e-310,   3.50977866e+064,   0.00000000e+000,
          0.00000000e+000],
       [              nan,               nan,   3.50977942e+064,
          1.11253916e-308],
       [ -0.00000000e+000,   2.32036407e+077,  -3.95252517e-323,
          0.00000000e+000],
       [  2.12199579e-314,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  1.75871011e-310,   3.50977866e+064,   0.00000000e+000,
          2.17292369e-311],
       [              nan,               nan,   3.50977942e+064,
          2.22507386e-308]])

In [2]:
for i in range(8):
    arr[i]=i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [3]:
arr[[4,3,0,6]] # 4th row 3rd row zeroth row and last before row

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [4]:
arr[[-3,-5,-7]] # indexing starts from backside

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [5]:
arr = np.arange(32).reshape((8,4))

In [7]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [8]:
arr[[1,2,3,4],[0,1,2,3]] # arr[[row index],[column index]]

array([ 4,  9, 14, 19])

In [11]:
arr[[1,5,7,2]][:,[0,3,1,2]] # (1,0)(1,3)(1,1)(1,2) # (5,0)(5,3)(5,1)(5,2)

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [12]:
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [13]:
arrr = np.arange(15).reshape((3,5))

In [14]:
arrr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
arrr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [16]:
a1 = np.random.randn(6,3)
np.dot(a1.T,a1)

array([[ 3.85017753,  3.8406089 , -0.53494431],
       [ 3.8406089 ,  9.9483914 , -1.35492608],
       [-0.53494431, -1.35492608,  1.42931666]])

In [17]:
b1 = np.arange(16).reshape((2,2,4))
b1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [18]:
b1.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [19]:
b1.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [2]:
#Universial Function or ufunc

datArray = np.arange(10)
np.sqrt(datArray)


array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [3]:
np.exp(datArray)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [6]:
x = np.random.randn(8)
y = np.random.randn(8)
x


array([ 0.39945753, -0.11830748,  3.02762091,  0.52280881, -1.09992367,
        0.40780415,  1.70536738, -0.21954954])

In [7]:
y

array([ 0.2006212 ,  2.71512405, -1.12733713, -0.88405749,  1.82776213,
        1.95350102, -0.71559127, -0.63140784])

In [8]:
np.maximum(x,y) #comparing with element wise comparsion  

array([ 0.39945753,  2.71512405,  3.02762091,  0.52280881,  1.82776213,
        1.95350102,  1.70536738, -0.21954954])

In [9]:
arrMul = np.random.randn(7)*5

In [10]:
arrMul

array([  0.82754422,  -2.69045688,  -1.85161361,  -0.37553323,
        11.1922941 ,  -3.2677058 ,  -6.58116099])

In [11]:
np.modf(arrMul) # it seperates arrays into multiple arrays with one contain int and other containing floating point 

(array([ 0.82754422, -0.69045688, -0.85161361, -0.37553323,  0.1922941 ,
        -0.2677058 , -0.58116099]),
 array([  0.,  -2.,  -1.,  -0.,  11.,  -3.,  -6.]))

In [13]:
points = np.arange(-5,5,0.01)
xs,ys = np.meshgrid(points,points)
print(ys)
print(xs)

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [14]:
import matplotlib.pyplot as plt
z = np.sqrt(xs**2 + ys**2)
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [15]:
plt.imshow(z,cmap=plt.cm.gray)
plt.colorbar()

In [17]:
plt.title("Image plot of $\sqrt{xs**2 + ys**2}$ for grid of values")

In [5]:
# conditional Array 
xarr = np.arange(1,1.5,0.1)
xarr

array([ 1. ,  1.1,  1.2,  1.3,  1.4])

In [6]:
yarr = np.arange(2,2.5,0.1)
yarr

array([ 2. ,  2.1,  2.2,  2.3,  2.4])

In [7]:
cond = np.array([True,False,True,True,False])

In [8]:
result = [(x if c else y) for x,y,c in zip(xarr,yarr,cond)]
result

[1.0,
 2.1000000000000001,
 1.2000000000000002,
 1.3000000000000003,
 2.4000000000000004]

In [9]:
result = np.where(cond,xarr,yarr) # based on condition (cond) being true we get values for xarr
result

array([ 1. ,  2.1,  1.2,  1.3,  2.4])

In [10]:
arrs = np.random.randn(4,4)
print(arrs)
np.where(arrs>0,2,-2)

[[-0.07170082 -1.01736674  1.22075954 -0.5879936 ]
 [ 1.60998794  1.09000866 -1.72235226 -1.43246952]
 [ 2.16632937  0.67803315  0.97550728 -0.25095468]
 [ 0.16443236  1.88299534  0.77059745  0.23317649]]


array([[-2, -2,  2, -2],
       [ 2,  2, -2, -2],
       [ 2,  2,  2, -2],
       [ 2,  2,  2,  2]])

In [11]:
np.where(arr>0,2,arr)

array([[  2.00000000e+000,  -3.11109878e+231,   2.00000000e+000,
          2.00000000e+000],
       [  2.00000000e+000,   2.00000000e+000,   2.00000000e+000,
          2.00000000e+000],
       [  2.00000000e+000,   2.00000000e+000,   2.00000000e+000,
          2.00000000e+000],
       [  2.00000000e+000,   2.00000000e+000,   2.00000000e+000,
          2.00000000e+000],
       [  2.00000000e+000,   2.00000000e+000,   2.00000000e+000,
          2.00000000e+000],
       [  2.00000000e+000,   2.00000000e+000,   2.00000000e+000,
          2.00000000e+000],
       [  2.00000000e+000,   2.00000000e+000,   2.00000000e+000,
          2.00000000e+000],
       [  2.00000000e+000,   2.00000000e+000,   2.00000000e+000,
          2.00000000e+000]])

In [ ]:
result = []
for i in range(n):
    if cond1[i] and cond2[i]:
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)
#-------------------------------------
# Nested Where condition

np.where(cond1 & cond2,0,
        np.where(cond1,1,
                np.where(cond2,2,3)))

#-------------------------------------

result = 1*cond1 + 2*cond2 + 3 * -(cond1 | cond2)

In [4]:
# Mathematical and Statistical Method 

arr = np.random.randn(5,4) # normally distributed data
print(arr)
print(arr.mean())
print(np.mean(arr))
print(arr.sum())
print(arr.mean(axis=1))  # 1 refers to row wise
print(arr.sum(0)) # 0 refers to column wise addition

[[ 1.52305924  0.1350278  -0.29704165  2.26043388]
 [ 0.56253616  0.66564348  1.15441428  2.01037256]
 [ 0.13353455 -1.01950295  0.61866577 -0.49964304]
 [ 0.91554787  0.69777331  0.89187633  0.84868893]
 [ 0.6397295   1.33571441  1.20687909 -1.07500936]]
0.635435008491
0.635435008491
12.7087001698
[ 0.90536982  1.09824162 -0.19173642  0.83847161  0.52682841]
[ 3.77440732  1.81465605  3.57479382  3.54484297]


In [7]:
narr = np.array([[0,1,2],[3,4,5],[5,6,7]])
print(narr)
print(narr.cumsum(0)) # cumulative addition along column wise
print(narr.cumprod(1)) # cumulative multiplication along row

[[0 1 2]
 [3 4 5]
 [5 6 7]]
[[ 0  1  2]
 [ 3  5  7]
 [ 8 11 14]]
[[  0   0   0]
 [  3  12  60]
 [  5  30 210]]


In [8]:
# Methods of Boolean
arrbool = np.random.randn(100)
(arrbool > 0).sum() # number of +ve value

47

In [9]:
bools = np.array([False,False,True,False])
print(bools.any())
print(bools.all())

True
False


In [11]:
arrsort = np.random.randn(8)
print(arrsort)
arrsort.sort()

[-1.80014161  0.50311672 -0.48727381 -0.57386274 -0.20431678  1.03857152
 -0.68292908 -0.23672336]
None


In [12]:
arrsort

array([-1.80014161, -0.68292908, -0.57386274, -0.48727381, -0.23672336,
       -0.20431678,  0.50311672,  1.03857152])

In [13]:
arrmulti = np.random.randn(5,3)

In [14]:
arrmulti

array([[-0.04943136, -2.3515299 ,  1.08390255],
       [ 0.26327507,  0.24112784, -0.8718168 ],
       [ 3.78307768, -0.90715262,  0.54256106],
       [ 1.20981768,  0.63570298,  0.50922957],
       [-0.33866864, -1.45137109,  0.86300991]])

In [17]:
arrmulti.sort(1) # axis = 1 is sorting the row 

In [18]:
arrmulti

array([[-2.3515299 , -0.04943136,  1.08390255],
       [-0.8718168 ,  0.24112784,  0.26327507],
       [-0.90715262,  0.54256106,  3.78307768],
       [ 0.50922957,  0.63570298,  1.20981768],
       [-1.45137109, -0.33866864,  0.86300991]])

In [19]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5% quantile 

-1.6560830189293365

In [20]:
#unique and other set logic
names = np.array(['bov','joe','dav','fov','fov','joe'])
np.unique(names)

array(['bov', 'dav', 'fov', 'joe'], 
      dtype='<U3')

In [21]:
ints = np.array([1,2,2,2,4,1,6,7,3])
np.unique(ints)

array([1, 2, 3, 4, 6, 7])

In [22]:
sorted(set(names))

['bov', 'dav', 'fov', 'joe']

In [24]:
values = np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6]) # it check existence of certain values in an array is present in another array

array([ True, False, False,  True,  True, False,  True], dtype=bool)

In [25]:
arrsave = np.arange(10)
np.save('Some_array',arrsave)

In [26]:
np.load('Some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.savez('multi_array.npz',a=arrsave,b=arrsave)

In [28]:
arch = np.load('multi_array.npz')
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# Saving and Loading Text files
# np.loadtxt
# np.genfromtxt
# arr = np.loadtxt('filename.txt',delimiter=',')
#! cat arrray.txt

In [30]:
# Linear Algebra
x = np.array([[1,2,3],[5,6,7]])
y = np.array([[1,2],[8,9],[6,7]])
x

array([[1, 2, 3],
       [5, 6, 7]])

In [31]:
y

array([[1, 2],
       [8, 9],
       [6, 7]])

In [32]:
arrMultiplication = x.dot(y) # Matrix Product
arrMultiplication

array([[ 35,  41],
       [ 95, 113]])

In [33]:
np.dot(x,np.ones(3))

array([  6.,  18.])

In [34]:
# Numpy.linalg helps in finding inverse and determinant

from numpy.linalg import inv,qr
X = np.random.randn(5,5)
mat = X.T.dot(X) # X^T * X
inv(mat)

array([[ 162.04684459,   42.38662055,  -75.7178926 , -115.26162076,
          17.04323425],
       [  42.38662055,   11.27127265,  -19.84565482,  -30.14371819,
           4.47839117],
       [ -75.7178926 ,  -19.84565482,   35.66362773,   53.69696135,
          -8.25152138],
       [-115.26162076,  -30.14371819,   53.69696135,   82.29338045,
         -11.8137333 ],
       [  17.04323425,    4.47839117,   -8.25152138,  -11.8137333 ,
           2.35860924]])

In [38]:
mat.dot(inv(mat))

array([[  1.00000000e+00,  -3.94085847e-14,   2.04048696e-14,
         -2.87394707e-14,   5.57732967e-15],
       [ -3.93772260e-14,   1.00000000e+00,   1.63520381e-14,
          1.11693918e-14,  -2.21931852e-15],
       [  2.23153638e-13,   1.56431113e-14,   1.00000000e+00,
         -6.83991053e-14,   1.93155001e-14],
       [  9.18646651e-14,  -2.36414491e-14,  -3.97405307e-15,
          1.00000000e+00,   7.98332755e-15],
       [ -1.91358242e-14,   1.23962869e-15,   3.11092448e-14,
          5.44411465e-14,   1.00000000e+00]])

In [39]:
q,r = qr(mat)

In [40]:
q

array([[-0.6573362 ,  0.078025  , -0.08486364, -0.00339876,  0.74471997],
       [ 0.086838  , -0.96317272,  0.16020018, -0.02828062,  0.19568747],
       [-0.34468467, -0.23741731, -0.72871036,  0.40472795, -0.3605579 ],
       [-0.63661576, -0.09340755,  0.33347934, -0.45641214, -0.51621206],
       [ 0.19047607, -0.03344344, -0.57000597, -0.79187872,  0.10306162]])

In [41]:
r

array([[-8.62079271,  0.44627744, -3.88399154, -8.9067714 ,  3.32696046],
       [ 0.        , -5.83477185, -2.89073052, -0.41139422, -1.10916169],
       [ 0.        ,  0.        , -7.58765615,  3.94941692, -7.00512596],
       [ 0.        ,  0.        ,  0.        , -0.19128639, -1.29384938],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.04369593]])

In [42]:
# diag / dot / trace / det / eig / inv / pinv / qr / svd / solve / lstsq - Other Linear Algebra Function (linalg)

In [43]:
# Random Number Generation
samples = np.random.normal(size=(4,4))
samples

array([[-1.55042406, -2.03233532, -0.91365565, -0.10385022],
       [-0.36277631, -0.38901028,  0.09489512, -0.71676009],
       [ 2.04797082,  0.72033599, -0.27734872,  0.6056616 ],
       [ 1.99092241,  1.03612704, -0.24190866,  0.8593484 ]])

In [44]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0,1) for _ in range(N)]

1 loop, best of 3: 1.1 s per loop


In [45]:
%timeit np.random.normal(size=N)

10 loops, best of 3: 39.1 ms per loop


In [ ]:
# seed / permutation / shuffle / rand / randint / randn / binomial / normal / beta / chisquare / gamma / uniform - Generate values or samples from these distribution

In [46]:
# Random Walks
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = i if random.randint(0,1) else -1
    position += step
    walk.append(position)

In [49]:
nsteps = 1000
draws = np.random.randint(0,2,size=nsteps)
steps = np.where(draws>0,1,-1)
walk = steps.cumsum()

In [50]:
walk.min()

-50

In [51]:
walk.max()

11

In [52]:
(np.abs(walk) >= 10).argmax() # it gives us the index or step when it reached 10 steps above zero

99

In [53]:
# Simulating many random walks at once 
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0,2,size=(nwalks,nsteps))
steps = np.where(draws>0,1,-1)
walks = steps.cumsum(1)
walks

array([[ -1,   0,   1, ...,  -2,  -1,  -2],
       [ -1,  -2,  -1, ..., -36, -35, -34],
       [ -1,   0,  -1, ...,  24,  23,  22],
       ..., 
       [ -1,  -2,  -1, ..., -56, -55, -56],
       [ -1,   0,   1, ..., -20, -21, -22],
       [  1,   0,   1, ...,  46,  45,  44]])

In [54]:
walks.max()

113

In [55]:
walks.min()

-113

In [56]:
hits30 = (np.abs(walks) >= 30).any(1)

In [57]:
hits30

array([False,  True,  True, ...,  True,  True,  True], dtype=bool)

In [58]:
hits30.sum() # number that hit 30 or -30

3404

In [59]:
crossing_times = (np.abs(walks[hits30])>=30).argmax(1)

In [60]:
crossing_times.mean()

499.05170387779083

In [61]:
steps = np.random.normal(loc=0,scale=0.25,size=(walks,nsteps))

TypeError: only integer scalar arrays can be converted to a scalar index